name: Run nf-tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v1
      
      - name: Set up nf-test
        uses: nf-core/setup-nf-test@v1
        with:
          install-pdiff: true
      
      - name: Run all nf-tests
        run: |
          nf-test test tests/modules/ --profile docker,test
          nf-test test tests/subworkflows/ --profile docker,test
          nf-test test tests/workflows/ --profile docker,test
      
      - name: Run e2e tests (main branch only)
        if: github.base_ref == 'main'
        run: |
          nf-test test tests/e2e/ --profile docker,test

